import * as THREE from 'three';
import RAPIER from '@dimforge/rapier3d-compat';
import { CONVEYORS, canonicalRebootSolution, createRebootPhysics, type BeltConnection, type RebootPart, type RebootPhysics } from './rebootPhysics';

const VERSION = 'reboot-level-01-v1';
type PartType = 'drive-wheel' | 'ramp';
type Placed = { data: RebootPart; object: THREE.Group };
type CanvasEx = HTMLCanvasElement & { __applyCanonicalSolution?: () => void; __start?: () => void; __advance?: (seconds: number) => void };

type Drag = { pointerId: number; source: 'inventory' | 'scene'; type: PartType; object: THREE.Group; placed?: Placed };

const material = (color: number, metalness = 0.08, roughness = 0.55) => new THREE.MeshStandardMaterial({ color, metalness, roughness });
const MAT = {
  cream: material(0xe8dfca, 0, .9), steel: material(0x78858e, .72, .3), dark: material(0x30383d, .45, .46), teal: material(0x3f8f91, .2, .4),
  red: material(0xc85c50, .05, .44), yellow: material(0xdcae4d, .12, .4), rubber: material(0x1f2427, .02, .9), ball: material(0xe5873f, .04, .35),
};

function finish(g: THREE.Object3D) { g.traverse((o) => { if (o instanceof THREE.Mesh) { o.castShadow = true; o.receiveShadow = true; } }); }
function rampMesh() { const g = new THREE.Group(); const deck = new THREE.Mesh(new THREE.BoxGeometry(2.84,.16,.62), MAT.steel); g.add(deck); const top = new THREE.Mesh(new THREE.BoxGeometry(2.78,.04,.5), MAT.rubber); top.position.y=.1; g.add(top); for (const z of [-.34,.34]) { const rail = new THREE.Mesh(new THREE.BoxGeometry(2.9,.18,.07), MAT.yellow); rail.position.set(0,.16,z); g.add(rail); } finish(g); return g; }
function wheelMesh() { const g = new THREE.Group(); const base = new THREE.Mesh(new THREE.BoxGeometry(1.05,.18,.58), MAT.teal); base.position.y=-.48; g.add(base); const rotor = new THREE.Mesh(new THREE.CylinderGeometry(.43,.43,.18,48), MAT.red); rotor.rotation.x=Math.PI/2; rotor.name='Rotor'; g.add(rotor); const hub = new THREE.Mesh(new THREE.CylinderGeometry(.11,.11,.3,24), MAT.steel); hub.rotation.x=Math.PI/2; g.add(hub); for(let i=0;i<8;i++){const a=i/8*Math.PI*2;const s=new THREE.Mesh(new THREE.BoxGeometry(.3,.045,.07),MAT.yellow);s.position.set(Math.cos(a)*.18,Math.sin(a)*.18,.11);s.rotation.z=a;g.add(s);} finish(g); return g; }
function conveyorMesh(id:string,w:number){const g=new THREE.Group();g.userData.conveyorId=id;const frame=new THREE.Mesh(new THREE.BoxGeometry(w,.2,.72),MAT.dark);frame.position.y=-.05;g.add(frame);const belt=new THREE.Mesh(new THREE.BoxGeometry(w-.12,.075,.58),MAT.rubber);belt.position.y=.1;g.add(belt);for(const x of [-w/2+.18,w/2-.18]){const r=new THREE.Mesh(new THREE.CylinderGeometry(.14,.14,.62,32),MAT.steel);r.rotation.x=Math.PI/2;r.position.set(x,.04,0);g.add(r);}finish(g);return g;}
function targetMesh(){const g=new THREE.Group();const ring=new THREE.Mesh(new THREE.TorusGeometry(.52,.075,16,64),MAT.red);ring.position.y=.12;g.add(ring);const cup=new THREE.Mesh(new THREE.BoxGeometry(1.1,.12,.72),MAT.teal);cup.position.y=-.43;g.add(cup);for(const x of [-.52,.52]){const s=new THREE.Mesh(new THREE.BoxGeometry(.1,.8,.72),MAT.teal);s.position.set(x,-.05,0);g.add(s);}finish(g);return g;}
function ballMesh(){const g=new THREE.Group();g.add(new THREE.Mesh(new THREE.SphereGeometry(.28,48,32),MAT.ball));const seam=new THREE.Mesh(new THREE.TorusGeometry(.282,.012,8,64),MAT.dark);seam.rotation.x=Math.PI/2;g.add(seam);finish(g);return g;}
function applyTransform(p:Placed){p.object.position.set(p.data.x,p.data.y,0);p.object.rotation.z=p.data.type==='ramp'?p.data.rotationZ:0;}

export async function startRebootApp(){
  await RAPIER.init();
  const host=document.querySelector<HTMLElement>('#app'); if(!host) throw new Error('app missing');
  host.innerHTML=`<main class="rb-shell"><header class="rb-top"><div class="rb-brand"><b>YOUNG INVENTOR</b><span>REBOOT</span></div><div class="rb-goal"><small>УРОВЕНЬ 1 · ПЕРЕДАЧА ДВИЖЕНИЯ</small><strong>Доставь оранжевый шар в приёмник</strong><span>Запусти три конвейера и построй путь.</span></div><div class="rb-actions"><button data-action="clear">Очистить</button><button data-action="stop">■ Стоп</button><button class="rb-run" data-action="run">▶ ПУСК</button></div></header><section class="rb-main"><aside class="rb-left"><h2>ДЕТАЛИ</h2><button class="rb-part" data-part="drive-wheel"><i class="wheel-mini"></i><span><b>ПРИВОДНОЕ КОЛЕСО</b><small>источник вращения</small></span><em data-count="drive-wheel">3</em></button><button class="rb-part" data-part="ramp"><i class="ramp-mini"></i><span><b>НАПРАВЛЯЮЩАЯ</b><small>траектория шара</small></span><em data-count="ramp">3</em></button><button class="rb-belt-tool" data-action="belt"><i>∞</i><span><b>ПРИВОДНОЙ РЕМЕНЬ</b><small>колесо → конвейер</small></span><em data-count="belt">3</em></button><div class="rb-help"><b>УПРАВЛЕНИЕ</b><p>Перетащи детали. Для ремня нажми «ремень», затем колесо и конвейер.</p></div></aside><section class="rb-stage-wrap"><canvas class="rb-canvas" data-version="${VERSION}" data-state="build" data-parts="0" data-belts="0"></canvas><div class="rb-toolbar" hidden><b data-selected>Деталь</b><button data-edit="left">↶</button><button data-edit="right">↷</button><button data-edit="flip">⇄</button><button data-edit="delete">✕</button></div><div class="rb-belt-status" hidden>РЕМЕНЬ: выбери приводное колесо</div><div class="rb-message">Собери механизм и нажми ПУСК</div><section class="rb-win" hidden><div>★</div><h2>Механизм работает!</h2><p>Шар достиг приёмника.</p><button data-action="stop">Вернуться к сборке</button></section></section><aside class="rb-right"><h2>СХЕМА</h2><div class="rb-rule"><span>1</span><p>Подключи каждый конвейер к своему колесу.</p></div><div class="rb-rule"><span>2</span><p>Направляющие ставятся свободно.</p></div><div class="rb-rule"><span>3</span><p>Победа — только реальный контакт шара с приёмником.</p></div><div class="rb-meter"><small>КОНВЕЙЕРЫ</small><div><i data-power="conveyor-a"></i><i data-power="conveyor-b"></i><i data-power="conveyor-c"></i></div></div></aside></section></main>`;

  const canvas=host.querySelector<CanvasEx>('.rb-canvas'); if(!canvas) throw new Error('canvas missing');
  const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
  const scene=new THREE.Scene();scene.background=new THREE.Color(0xd8ccb5);const camera=new THREE.PerspectiveCamera(34,1,.1,50);camera.position.set(0,2.15,15.4);camera.lookAt(0,2,0);scene.add(new THREE.HemisphereLight(0xfff8e7,0x75695d,2));const sun=new THREE.DirectionalLight(0xffefd0,4.4);sun.position.set(-4,8,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);
  const panel=new THREE.Mesh(new THREE.BoxGeometry(13.2,5.9,.22),MAT.cream);panel.position.set(0,2.1,-.7);scene.add(panel);const grid=new THREE.GridHelper(12.5,25,0xa99c85,0xc8bda8);grid.rotation.x=Math.PI/2;grid.position.set(0,2.1,-.56);scene.add(grid);const floor=new THREE.Mesh(new THREE.BoxGeometry(13.2,.18,1.3),MAT.dark);floor.position.set(0,-.18,0);scene.add(floor);
  const conveyorObjects=new Map<string,THREE.Group>();for(const c of CONVEYORS){const g=conveyorMesh(c.id,c.width);g.position.set(c.x,c.y,0);scene.add(g);conveyorObjects.set(c.id,g);}const target=targetMesh();target.position.set(5.72,3.58,0);scene.add(target);const ball=ballMesh();ball.position.set(-5.15,1.12,0);scene.add(ball);

  const parts:Placed[]=[];const belts:BeltConnection[]=[];const beltLines=new Map<string,THREE.Line>();const ray=new THREE.Raycaster();const ndc=new THREE.Vector2();const plane=new THREE.Plane(new THREE.Vector3(0,0,1),0);let drag:Drag|null=null;let selected:Placed|null=null;let beltMode=false;let beltSource:Placed|null=null;let sim:RebootPhysics|null=null;let id=1;let previous=performance.now();let accumulator=0;
  const worldPoint=(x:number,y:number)=>{const r=canvas.getBoundingClientRect();ndc.set((x-r.left)/r.width*2-1,-((y-r.top)/r.height*2-1));ray.setFromCamera(ndc,camera);const p=new THREE.Vector3();return ray.ray.intersectPlane(plane,p)?p:null;};const inside=(x:number,y:number)=>{const r=canvas.getBoundingClientRect();return x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom;};const remaining=(type:PartType)=>3-parts.filter(p=>p.data.type===type).length;
  const refresh=()=>{canvas.dataset.parts=String(parts.length);canvas.dataset.belts=String(belts.length);for(const type of ['drive-wheel','ramp'] as PartType[]){const el=host.querySelector(`[data-count="${type}"]`);if(el)el.textContent=String(remaining(type));host.querySelector<HTMLButtonElement>(`.rb-part[data-part="${type}"]`)!.disabled=remaining(type)<=0||!!sim;}const bc=host.querySelector('[data-count="belt"]');if(bc)bc.textContent=String(3-belts.length);host.querySelector<HTMLButtonElement>('[data-action="belt"]')!.disabled=belts.length>=3||!!sim;for(const c of CONVEYORS)host.querySelector(`[data-power="${c.id}"]`)?.classList.toggle('on',belts.some(b=>b.conveyorId===c.id));const tb=host.querySelector<HTMLElement>('.rb-toolbar')!;tb.hidden=!selected||!!sim;if(selected)tb.querySelector<HTMLElement>('[data-selected]')!.textContent=selected.data.type==='ramp'?'Направляющая':'Приводное колесо';};
  const select=(p:Placed|null)=>{selected=p;refresh();};const clone=(type:PartType)=>type==='ramp'?rampMesh():wheelMesh();
  const rebuildBelts=()=>{for(const line of beltLines.values()){scene.remove(line);line.geometry.dispose();}beltLines.clear();for(const b of belts){const w=parts.find(p=>p.data.id===b.wheelId);const c=CONVEYORS.find(c=>c.id===b.conveyorId);if(!w||!c)continue;const pts=[new THREE.Vector3(w.data.x,w.data.y,.4),new THREE.Vector3(c.x-c.width/2+.2,c.y-.18,.4)];const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:0x302b27}));scene.add(line);beltLines.set(b.id,line);}};
  const addPart=(type:PartType,p:THREE.Vector3)=>{if(remaining(type)<=0)return;const data:RebootPart=type==='ramp'?{id:`r${id++}`,type,x:p.x,y:p.y,rotationZ:0}:{id:`w${id++}`,type,x:p.x,y:p.y,direction:1};const object=clone(type);const placed={data,object};scene.add(object);parts.push(placed);applyTransform(placed);select(placed);};
  const removePart=(p:Placed)=>{scene.remove(p.object);parts.splice(parts.indexOf(p),1);for(const b of [...belts])if(b.wheelId===p.data.id)belts.splice(belts.indexOf(b),1);if(selected===p)selected=null;rebuildBelts();refresh();};
  const pick=(event:PointerEvent)=>{const r=canvas.getBoundingClientRect();ndc.set((event.clientX-r.left)/r.width*2-1,-((event.clientY-r.top)/r.height*2-1));ray.setFromCamera(ndc,camera);const objs:THREE.Object3D[]=[];const map=new Map<THREE.Object3D,Placed>();for(const p of parts)p.object.traverse(o=>{if(o instanceof THREE.Mesh){objs.push(o);map.set(o,p);}});for(const [cid,g] of conveyorObjects)g.traverse(o=>{if(o instanceof THREE.Mesh){o.userData.cid=cid;objs.push(o);}});const h=ray.intersectObjects(objs,false)[0];if(!h)return{};const p=map.get(h.object);if(p)return{part:p};return{conveyorId:h.object.userData.cid as string|undefined};};
  const stopBelt=()=>{beltMode=false;beltSource=null;host.querySelector<HTMLElement>('.rb-belt-status')!.hidden=true;host.querySelector('[data-action="belt"]')?.classList.remove('active');};
  const beltTap=(event:PointerEvent)=>{if(!beltMode)return false;const hit=pick(event);const status=host.querySelector<HTMLElement>('.rb-belt-status')!;if(!beltSource){if(hit.part?.data.type==='drive-wheel'){beltSource=hit.part;status.textContent='РЕМЕНЬ: выбери конвейер';}return true;}if(hit.conveyorId&&!belts.some(b=>b.conveyorId===hit.conveyorId)&&!belts.some(b=>b.wheelId===beltSource!.data.id)){belts.push({id:`b${id++}`,wheelId:beltSource.data.id,conveyorId:hit.conveyorId});rebuildBelts();stopBelt();refresh();}return true;};

  host.querySelectorAll<HTMLButtonElement>('.rb-part').forEach(btn=>btn.addEventListener('pointerdown',event=>{if(sim||drag)return;const type=btn.dataset.part as PartType;if(remaining(type)<=0)return;event.preventDefault();const object=clone(type);object.visible=false;scene.add(object);drag={pointerId:event.pointerId,source:'inventory',type,object};}));
  window.addEventListener('pointermove',event=>{if(!drag||drag.pointerId!==event.pointerId)return;event.preventDefault();const p=worldPoint(event.clientX,event.clientY);if(!p||!inside(event.clientX,event.clientY)){if(drag.source==='inventory')drag.object.visible=false;return;}p.x=THREE.MathUtils.clamp(p.x,-5.9,5.9);p.y=THREE.MathUtils.clamp(p.y,.05,4.7);drag.object.visible=true;drag.object.position.set(p.x,p.y,0);if(drag.placed){drag.placed.data.x=p.x;drag.placed.data.y=p.y;rebuildBelts();}}, {passive:false});
  window.addEventListener('pointerup',event=>{if(!drag||drag.pointerId!==event.pointerId)return;const d=drag;drag=null;if(d.source==='inventory'){const p=worldPoint(event.clientX,event.clientY);scene.remove(d.object);if(p&&inside(event.clientX,event.clientY))addPart(d.type,p);}refresh();},{passive:false});
  canvas.addEventListener('pointerdown',event=>{if(sim)return;if(beltTap(event))return;const hit=pick(event);if(!hit.part){select(null);return;}select(hit.part);drag={pointerId:event.pointerId,source:'scene',type:hit.part.data.type,object:hit.part.object,placed:hit.part};});

  const cleanup=()=>{sim?.free();sim=null;ball.position.set(-5.15,1.12,0);ball.quaternion.identity();canvas.dataset.state='build';host.querySelector<HTMLElement>('.rb-win')!.hidden=true;refresh();};
  const start=()=>{if(sim)return;stopBelt();sim=createRebootPhysics(parts.map(p=>p.data),belts);canvas.dataset.state='run';accumulator=0;host.querySelector<HTMLElement>('.rb-message')!.textContent=belts.length<3?'Не все конвейеры подключены. Посмотрим, что произойдёт.':'Машина запущена';refresh();};
  const sync=()=>{if(!sim)return;const p=sim.ballBody.translation(),q=sim.ballBody.rotation();ball.position.set(p.x,p.y,p.z);ball.quaternion.set(q.x,q.y,q.z,q.w);if(sim.state.won){canvas.dataset.state='won';host.querySelector<HTMLElement>('.rb-win')!.hidden=false;}if(sim.state.ballOut)host.querySelector<HTMLElement>('.rb-message')!.textContent='Шар ушёл с маршрута. Нажми Стоп и перестрой.';};

  host.addEventListener('click',event=>{const el=event.target as HTMLElement;const action=el.closest<HTMLElement>('[data-action]')?.dataset.action;const edit=el.closest<HTMLElement>('[data-edit]')?.dataset.edit;if(action==='run')start();if(action==='stop')cleanup();if(action==='clear'&&!sim){for(const p of [...parts])removePart(p);belts.splice(0);rebuildBelts();stopBelt();refresh();}if(action==='belt'&&!sim){beltMode=!beltMode;beltSource=null;const s=host.querySelector<HTMLElement>('.rb-belt-status')!;s.hidden=!beltMode;s.textContent='РЕМЕНЬ: выбери приводное колесо';el.closest('[data-action="belt"]')?.classList.toggle('active',beltMode);}if(edit&&selected&&!sim){if(edit==='delete'){removePart(selected);return;}if(selected.data.type==='ramp'){if(edit==='left')selected.data.rotationZ+=Math.PI/18;if(edit==='right')selected.data.rotationZ-=Math.PI/18;}else if(edit==='flip')selected.data.direction=selected.data.direction===1?-1:1;applyTransform(selected);}});

  canvas.__applyCanonicalSolution=()=>{if(sim)return;for(const p of [...parts])removePart(p);belts.splice(0);const c=canonicalRebootSolution();for(const data of c.parts){const object=clone(data.type);const placed={data:{...data} as RebootPart,object};parts.push(placed);scene.add(object);applyTransform(placed);}belts.push(...c.belts.map(b=>({...b})));rebuildBelts();select(null);refresh();};canvas.__start=start;canvas.__advance=(seconds:number)=>{sim?.advance(seconds);sync();};canvas.dataset.physics='rapier3d-cleanroom-reboot-v1';canvas.dataset.layout='original-benchmark-not-tim-level-data';
  const resize=()=>{const r=canvas.getBoundingClientRect();renderer.setSize(Math.max(1,r.width),Math.max(1,r.height),false);camera.aspect=Math.max(1,r.width)/Math.max(1,r.height);camera.updateProjectionMatrix();};new ResizeObserver(resize).observe(canvas);resize();refresh();
  const loop=(now:number)=>{requestAnimationFrame(loop);const dt=Math.min((now-previous)/1000,.08);previous=now;if(sim&&!sim.state.won&&!sim.state.ballOut){accumulator+=dt;while(accumulator>=1/120){sim.step();accumulator-=1/120;}sync();}renderer.render(scene,camera);};requestAnimationFrame(loop);
}
