import * as THREE from 'three';

type Pickable={root:THREE.Object3D; home:THREE.Vector3};
const C={bg:0xf4f4f2,floor:0xe9e9e7,al:0xbfc2c3,al2:0xd5d7d7,dark:0x85898a,rope:0x9b9b96,red:0xc94c43,white:0xe9e9e7};

function standard(color:number,metalness=.52,roughness=.42){return new THREE.MeshStandardMaterial({color,metalness,roughness});}
function physical(color:number,roughness=.18,transmission=.82,opacity=.3){return new THREE.MeshPhysicalMaterial({color,roughness,metalness:0,transmission,transparent:true,opacity,thickness:.18,ior:1.5});}
function mesh<G extends THREE.BufferGeometry>(g:G,m:THREE.Material,shadow=false){const o=new THREE.Mesh(g,m);o.castShadow=shadow;o.receiveShadow=false;return o;}
function box(w:number,h:number,d:number,m:THREE.Material){return mesh(new THREE.BoxGeometry(w,h,d,3,3,2),m);}
function cyl(r:number,h:number,m:THREE.Material,s=64){return mesh(new THREE.CylinderGeometry(r,r,h,s),m);}
function torus(r:number,t:number,m:THREE.Material){return mesh(new THREE.TorusGeometry(r,t,20,80),m);}
function sphere(r:number,m:THREE.Material){return mesh(new THREE.SphereGeometry(r,64,40),m);}
function capsule(r:number,l:number,m:THREE.Material){return mesh(new THREE.CapsuleGeometry(r,l,10,24),m);}
function addBlob(scene:THREE.Scene,x:number,y:number,sx:number,sy:number,z=-.62,opacity=.055){const mat=new THREE.MeshBasicMaterial({color:0x6f7272,transparent:true,opacity,depthWrite:false});const p=mesh(new THREE.CircleGeometry(1,64),mat);p.scale.set(sx,sy,1);p.position.set(x,y,z);scene.add(p);return p;}
function tube(points:THREE.Vector3[],radius:number,m:THREE.Material){return mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),96,radius,10,false),m);}

function pedestal(){const g=new THREE.Group();const metal=standard(C.al2,.28,.5);const top=box(2.35,.26,1.0,metal);top.position.y=2.85;g.add(top);const neck=cyl(.23,4.75,metal,48);neck.position.y=.38;g.add(neck);const collar=cyl(.42,.18,standard(C.al,.42,.45));collar.position.y=-1.95;g.add(collar);const base=box(2.1,.42,1.12,standard(C.al,.45,.46));base.position.y=-2.42;g.add(base);return g;}
function ramp(){const g=new THREE.Group();const top=box(7.25,.34,.62,standard(C.al,.65,.34));top.rotation.z=THREE.MathUtils.degToRad(18.5);g.add(top);const underside=box(7.0,.07,.64,standard(C.dark,.62,.36));underside.rotation.z=top.rotation.z;underside.position.y=-.19;g.add(underside);const pin=cyl(.34,.84,standard(C.dark,.72,.28));pin.rotation.x=Math.PI/2;pin.position.set(3.35,1.12,.06);g.add(pin);const washer=torus(.36,.06,standard(C.al2,.58,.31));washer.position.copy(pin.position);g.add(washer);return g;}
function pulley(){const g=new THREE.Group();const m=standard(C.al,.68,.31);g.add(torus(.72,.16,m));const groove=torus(.72,.035,standard(C.dark,.45,.5));groove.position.z=.16;g.add(groove);const hub=cyl(.15,.44,standard(C.dark,.7,.26));hub.rotation.x=Math.PI/2;g.add(hub);for(let i=0;i<6;i++){const s=box(.76,.055,.1,standard(C.al2,.48,.38));s.rotation.z=i*Math.PI/3;g.add(s);}const axle=cyl(.09,.7,standard(C.dark,.75,.22));axle.rotation.x=Math.PI/2;g.add(axle);return g;}
function weight(){const g=new THREE.Group();const body=box(1.18,1.55,.78,standard(C.al,.58,.4));g.add(body);const cap=box(.52,.15,.4,standard(C.dark,.65,.3));cap.position.y=.85;g.add(cap);const eye=torus(.13,.035,standard(C.dark,.6,.34));eye.position.y=1.0;g.add(eye);return g;}
function fan(){const g=new THREE.Group();const metal=standard(C.al,.58,.37);const guard=new THREE.Group();guard.name='fan-guard';guard.add(torus(1.48,.075,metal));guard.add(torus(1.31,.035,standard(C.al2,.42,.5)));for(let i=0;i<12;i++){const s=box(2.55,.028,.055,standard(C.al2,.38,.52));s.rotation.z=i*Math.PI/12;guard.add(s);}g.add(guard);const blades=new THREE.Group();blades.name='fan-blades';for(let i=0;i<3;i++){const shape=new THREE.Shape();shape.moveTo(.08,.12);shape.bezierCurveTo(.35,.15,.78,.42,1.02,.92);shape.bezierCurveTo(.72,1.1,.3,.96,.1,.38);shape.closePath();const b=mesh(new THREE.ExtrudeGeometry(shape,{depth:.08,bevelEnabled:true,bevelSize:.025,bevelThickness:.025,bevelSegments:2}),standard(C.dark,.5,.42));b.rotation.z=i*Math.PI*2/3-.15;b.position.z=.02;blades.add(b);}g.add(blades);const hub=cyl(.3,.5,standard(C.dark,.7,.28));hub.rotation.x=Math.PI/2;g.add(hub);const motor=cyl(.48,.58,standard(C.al2,.52,.44));motor.rotation.x=Math.PI/2;motor.position.z=-.46;g.add(motor);const post=cyl(.1,2.72,metal,40);post.position.y=-2.84;g.add(post);const neck=box(.65,.14,.32,metal);neck.position.y=-1.54;g.add(neck);const base=box(1.72,.25,.86,standard(C.al,.48,.44));base.position.y=-4.23;g.add(base);return g;}
function glove(){const g=new THREE.Group();const red=standard(C.red,.06,.48);const palm=capsule(.56,.8,red);palm.scale.set(1.05,1,.72);palm.position.y=1.26;g.add(palm);for(let i=0;i<4;i++){const f=capsule(.15,.55,red);f.scale.z=.72;f.position.set(-.37+i*.25,2.06+Math.sin(i*.8)*.08,0);f.rotation.z=THREE.MathUtils.degToRad(-8+i*3);g.add(f);}const thumb=capsule(.19,.52,red);thumb.scale.z=.72;thumb.rotation.z=THREE.MathUtils.degToRad(-58);thumb.position.set(.61,1.43,0);g.add(thumb);const cuff=cyl(.48,.36,red,48);cuff.position.y=.38;g.add(cuff);const springPts:THREE.Vector3[]=[];for(let i=0;i<170;i++){const u=i/169;const a=u*Math.PI*13.5;springPts.push(new THREE.Vector3(Math.cos(a)*.47,-.05-u*2.5,Math.sin(a)*.11));}const spring=tube(springPts,.045,standard(C.dark,.78,.24));spring.name='glove-spring';g.add(spring);const base=box(1.75,.28,.9,standard(C.al,.5,.45));base.position.y=-2.72;g.add(base);return g;}
function candle(){const g=new THREE.Group();const body=cyl(.3,1.78,standard(C.white,.02,.78));body.position.y=-.04;g.add(body);const top=cyl(.3,.08,standard(0xf1f1ef,.02,.82));top.position.y=.87;g.add(top);const wick=cyl(.025,.18,standard(0x424242,.0,.9),16);wick.position.y=1.0;g.add(wick);const flameMat=new THREE.MeshStandardMaterial({color:0xffd18a,emissive:0xff9b42,emissiveIntensity:2.5,roughness:.15});const f=sphere(.16,flameMat);f.scale.set(.72,1.55,.72);f.position.y=1.28;g.add(f);const light=new THREE.PointLight(0xffb05c,.5,2.8,2.2);light.position.y=1.3;g.add(light);return g;}
function flashlight(){const g=new THREE.Group();const body=cyl(.31,1.55,standard(C.al,.62,.34));body.rotation.z=Math.PI/2;g.add(body);for(const x of[-.45,0,.45]){const ring=torus(.31,.025,standard(C.dark,.52,.42));ring.rotation.y=Math.PI/2;ring.position.x=x;g.add(ring);}const head=cyl(.48,.46,standard(C.dark,.62,.3));head.rotation.z=Math.PI/2;head.position.x=.96;g.add(head);const bezel=torus(.38,.055,standard(C.al2,.62,.3));bezel.rotation.y=Math.PI/2;bezel.position.x=1.19;g.add(bezel);const lens=cyl(.33,.035,physical(0xdde5e7,.08,.75,.42),64);lens.rotation.z=Math.PI/2;lens.position.x=1.2;g.add(lens);g.rotation.z=THREE.MathUtils.degToRad(31);return g;}
function magnifier(){const g=new THREE.Group();g.add(torus(.76,.08,standard(C.al,.58,.34)));const lens=mesh(new THREE.CircleGeometry(.675,80),physical(0xe4ebec,.04,.88,.24));lens.position.z=.008;g.add(lens);const stem=cyl(.105,1.52,standard(C.dark,.58,.34),48);stem.rotation.z=THREE.MathUtils.degToRad(-41);stem.position.set(.74,-1.12,0);g.add(stem);const grip=capsule(.14,.52,standard(C.al,.46,.43));grip.rotation.z=THREE.MathUtils.degToRad(-41);grip.position.set(1.13,-1.58,0);g.add(grip);return g;}
function button(){const g=new THREE.Group();const base=cyl(.64,.2,standard(C.al,.38,.48));base.rotation.x=Math.PI/2;g.add(base);const collar=cyl(.45,.17,standard(C.al2,.35,.5));collar.rotation.x=Math.PI/2;collar.position.z=.12;g.add(collar);const top=cyl(.34,.18,standard(C.red,.08,.4));top.rotation.x=Math.PI/2;top.position.z=.25;g.add(top);return g;}
function basket(){const g=new THREE.Group();const m=standard(C.dark,.42,.5);const w=1.45,h=1.25;for(let i=0;i<6;i++){const v=box(.055,h,.48,m);v.position.set(-w/2+i*w/5,0,0);g.add(v);}for(let j=0;j<4;j++){const hh=box(w,.055,.48,m);hh.position.y=-h/2+j*h/3;g.add(hh);}const bottom=box(w+.1,.09,.5,m);bottom.position.y=-h/2-.04;g.add(bottom);return g;}
function rope(scene:THREE.Scene){const m=standard(C.rope,.02,.9);const p=[new THREE.Vector3(.2,5.35,.18),new THREE.Vector3(.55,5.8,.18),new THREE.Vector3(.9,5.25,.18),new THREE.Vector3(.72,1.65,.18)];const r=tube(p,.055,m);scene.add(r);return r;}

function installDom(){document.body.innerHTML=`<main class="clean01v2-shell"><section class="clean01v2-stage"><canvas id="clean01v2-canvas"></canvas></section><header class="clean01v2-top"><div><button id="clean01v2-menu" class="clean01v2-menu" aria-label="Меню"><span></span><span></span><span></span></button><b>01</b></div><button id="clean01v2-play" class="clean01v2-play" aria-label="Запустить">▶</button></header><footer class="clean01v2-shelf"><div class="clean01v2-parts">${['ball','ramp','rope','pulley','fan','candle','flashlight','magnifier','button','basket'].map((n,i)=>`<button data-part="${n}" aria-label="Деталь ${i+1}"><i class="p-${n}"></i></button>`).join('')}</div></footer><div class="clean01v2-toast" id="clean01v2-toast"></div></main>`;}

export function installCleanMinimalLevel01V2():void{
 installDom();
 const canvas=document.querySelector<HTMLCanvasElement>('#clean01v2-canvas')!;
 const stage=document.querySelector<HTMLElement>('.clean01v2-stage')!;
 const play=document.querySelector<HTMLButtonElement>('#clean01v2-play')!;
 const toast=document.querySelector<HTMLElement>('#clean01v2-toast')!;
 const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});
 renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.98;renderer.shadowMap.enabled=false;
 const scene=new THREE.Scene();scene.background=new THREE.Color(C.bg);
 const camera=new THREE.PerspectiveCamera(19,4/3,.1,100);camera.position.set(0,.25,43.5);camera.lookAt(0,.05,0);
 scene.add(new THREE.HemisphereLight(0xffffff,0xd6d6d2,3.0));const key=new THREE.PointLight(0xffffff,34,80,1.55);key.position.set(-10,14,23);scene.add(key);const fill=new THREE.PointLight(0xffffff,16,70,1.7);fill.position.set(13,7,18);scene.add(fill);
 const wall=mesh(new THREE.PlaneGeometry(42,28),standard(C.bg,0,.96));wall.position.z=-1.15;scene.add(wall);const floor=mesh(new THREE.PlaneGeometry(42,6),standard(C.floor,0,.92));floor.position.set(0,-6.05,-.82);scene.add(floor);
 const picks:Pickable[]=[];const reg=(o:THREE.Object3D,x:number,y:number,z=0)=>{o.position.set(x,y,z);scene.add(o);picks.push({root:o,home:o.position.clone()});return o;};
 reg(pedestal(),-9.6,-.1,.04);const ball=sphere(.56,standard(0xc9cccd,.82,.19));ball.position.set(-9.6,3.25,.15);scene.add(ball);picks.push({root:ball,home:ball.position.clone()});
 const r=reg(ramp(),-4.6,3.3,.08);const p=reg(pulley(),.2,5.2,.12);const w=reg(weight(),.72,.78,.08);rope(scene);
 const f=reg(fan(),8.0,.95,.02);const gl=reg(glove(),-3.8,-3.0,.14);const ca=reg(candle(),-.7,-3.72,.18);const fl=reg(flashlight(),2.7,-3.78,.18);const mg=reg(magnifier(),5.25,-3.25,.16);const bt=reg(button(),8.0,-4.65,.16);const ba=reg(basket(),10.5,-3.78,.05);
 addBlob(scene,-9.6,-2.68,1.0,.18);addBlob(scene,-4.3,1.15,3.2,.14);addBlob(scene,.65,-.15,.8,.18);addBlob(scene,8.0,-3.35,1.2,.16);addBlob(scene,-3.8,-5.05,.9,.16);addBlob(scene,-.7,-4.75,.45,.12);addBlob(scene,2.8,-4.65,.8,.13);addBlob(scene,5.3,-4.45,.8,.13);addBlob(scene,8.0,-5.15,.72,.12);addBlob(scene,10.5,-4.55,.82,.12);
 const ray=new THREE.Raycaster(),ptr=new THREE.Vector2(),plane=new THREE.Plane(new THREE.Vector3(0,0,1),0),hit=new THREE.Vector3();let selected:THREE.Object3D|null=null;let offset=new THREE.Vector3();let pid:number|null=null;let running=false;let started=performance.now();
 const setSelected=(root:THREE.Object3D|null)=>{selected=root;for(const item of picks)item.root.traverse(o=>{if(o instanceof THREE.Mesh && o.material instanceof THREE.MeshStandardMaterial)o.material.emissive.setHex(item.root===root?0x0d0d0d:0x000000);});};
 const point=(e:PointerEvent)=>{const rr=canvas.getBoundingClientRect();ptr.set((e.clientX-rr.left)/rr.width*2-1,-((e.clientY-rr.top)/rr.height*2-1));ray.setFromCamera(ptr,camera);};
 canvas.addEventListener('pointerdown',e=>{point(e);const hits=ray.intersectObjects(picks.map(x=>x.root),true);if(!hits.length){setSelected(null);return;}let o:THREE.Object3D=hits[0].object;while(o.parent && !picks.some(x=>x.root===o))o=o.parent;setSelected(o);if(ray.ray.intersectPlane(plane,hit)){offset.copy(o.position).sub(hit);pid=e.pointerId;canvas.setPointerCapture(pid);}});
 canvas.addEventListener('pointermove',e=>{if(pid!==e.pointerId||!selected||running)return;point(e);if(ray.ray.intersectPlane(plane,hit)){selected.position.copy(hit.add(offset));selected.position.x=THREE.MathUtils.clamp(selected.position.x,-11.5,11.5);selected.position.y=THREE.MathUtils.clamp(selected.position.y,-5.1,5.8);}});
 canvas.addEventListener('pointerup',e=>{if(pid===e.pointerId)pid=null;});canvas.addEventListener('pointercancel',()=>pid=null);canvas.addEventListener('wheel',e=>{if(!selected||running)return;e.preventDefault();selected.rotation.z+=e.deltaY>0?-.055:.055;},{passive:false});
 const show=(s:string)=>{toast.textContent=s;toast.classList.add('show');window.setTimeout(()=>toast.classList.remove('show'),1200);};
 document.querySelector('#clean01v2-menu')?.addEventListener('click',()=>show('Меню появится после утверждения визуального стандарта'));
 play.addEventListener('click',()=>{running=!running;started=performance.now();play.textContent=running?'■':'▶';play.classList.toggle('running',running);if(!running){for(const item of picks)item.root.position.copy(item.home);gl.rotation.z=0;w.position.copy(picks.find(x=>x.root===w)!.home);}});
 document.querySelectorAll<HTMLButtonElement>('.clean01v2-parts button').forEach(b=>b.addEventListener('click',()=>show('Перетащи соответствующую деталь на игровом поле')));
 function resize(){const rect=stage.getBoundingClientRect();const dpr=Math.min(devicePixelRatio,2);renderer.setSize(rect.width,rect.height,false);camera.aspect=rect.width/rect.height;camera.updateProjectionMatrix();if(canvas.width!==Math.floor(rect.width*dpr)||canvas.height!==Math.floor(rect.height*dpr))renderer.setPixelRatio(dpr);}window.addEventListener('resize',resize);resize();
 function frame(now:number){const t=(now-started)/1000;const blades=f.getObjectByName('fan-blades');if(blades&&running)blades.rotation.z=t*4.6;if(running){gl.position.y=picks.find(x=>x.root===gl)!.home.y+Math.sin(t*9)*Math.exp(-t*.5)*.22;w.position.y=picks.find(x=>x.root===w)!.home.y-Math.min(t*.32,1.4);}renderer.render(scene,camera);requestAnimationFrame(frame);}requestAnimationFrame(frame);
 void r;void p;void ca;void fl;void mg;void bt;void ba;
}
