import * as THREE from 'three';

type Draggable={root:THREE.Object3D; home:THREE.Vector3};

const RED=0xc94c43;
const ALUMINIUM=0xbec0c1;
const DARK=0x8f9293;
const WHITE=0xe3e4e3;
const ROPE=0x999994;

function mat(color:number,metalness=.55,roughness=.38){return new THREE.MeshStandardMaterial({color,metalness,roughness});}
function box(w:number,h:number,d:number,m:THREE.Material,r=.08){const g=new THREE.BoxGeometry(w,h,d,4,4,2);const mesh=new THREE.Mesh(g,m);mesh.castShadow=true;mesh.receiveShadow=true;return mesh;}
function cyl(r:number,h:number,m:THREE.Material,segments=48){const mesh=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,segments),m);mesh.castShadow=true;mesh.receiveShadow=true;return mesh;}
function sphere(r:number,m:THREE.Material){const mesh=new THREE.Mesh(new THREE.SphereGeometry(r,48,32),m);mesh.castShadow=true;mesh.receiveShadow=true;return mesh;}
function groupAt(x:number,y:number,z=0){const g=new THREE.Group();g.position.set(x,y,z);return g;}

function makePedestal(){const g=new THREE.Group();const m=mat(0xd3d5d4,.25,.48);const top=box(2.1,.28,.9,m);top.position.y=2.62;g.add(top);const stem=box(.72,4.7,.72,mat(0xd9dada,.2,.52));stem.position.y=.18;g.add(stem);const base=box(2.2,.58,1.12,mat(0xc3c5c4,.28,.46));base.position.y=-2.42;g.add(base);return g;}
function makeRamp(){const g=new THREE.Group();const rail=box(6.8,.42,.55,mat(ALUMINIUM,.65,.34));rail.rotation.z=THREE.MathUtils.degToRad(19);g.add(rail);const pin=cyl(.34,.78,mat(0xa5a7a8,.7,.28));pin.rotation.x=Math.PI/2;pin.position.set(3.05,1.02,.1);g.add(pin);return g;}
function makePulley(){const g=new THREE.Group();const ring=new THREE.Mesh(new THREE.TorusGeometry(.62,.17,20,64),mat(0xb9bbbb,.65,.32));ring.castShadow=true;g.add(ring);const hub=cyl(.15,.42,mat(DARK,.72,.25));hub.rotation.x=Math.PI/2;g.add(hub);for(let i=0;i<4;i++){const spoke=box(.78,.08,.12,mat(0xaeb0b1,.6,.34));spoke.rotation.z=i*Math.PI/2;g.add(spoke);}return g;}
function makeWeight(){const g=new THREE.Group();g.add(box(1.2,1.5,.72,mat(0xbfc0c0,.55,.42)));const cap=box(.56,.16,.4,mat(DARK,.65,.3));cap.position.y=.83;g.add(cap);return g;}
function makeFan(){const g=new THREE.Group();const metal=mat(0xbfc1c1,.58,.38);const ring=new THREE.Mesh(new THREE.TorusGeometry(1.42,.11,18,64),metal);ring.castShadow=true;g.add(ring);const hub=cyl(.31,.42,mat(DARK,.7,.28));hub.rotation.x=Math.PI/2;g.add(hub);const blades=new THREE.Group();blades.name='fan-blades';for(let i=0;i<3;i++){const b=box(.34,1.1,.11,mat(0xaeb0b1,.62,.35));b.position.y=.62;b.rotation.z=THREE.MathUtils.degToRad(-22);const arm=new THREE.Group();arm.rotation.z=i*Math.PI*2/3;arm.add(b);blades.add(arm);}g.add(blades);const post=box(.18,2.7,.18,metal);post.position.y=-2.7;g.add(post);const base=box(1.8,.26,.8,mat(0xb9babb,.55,.43));base.position.y=-4.05;g.add(base);return g;}
function makeGlove(){const g=new THREE.Group();const red=mat(RED,.15,.42);const palm=box(1.05,1.02,.62,red);palm.position.y=1.2;g.add(palm);for(let i=0;i<4;i++){const f=cyl(.16,.72,red,32);f.rotation.z=THREE.MathUtils.degToRad(-8+i*5);f.position.set(-.38+i*.25,2.02+i*.03,0);g.add(f);}const thumb=cyl(.2,.68,red,32);thumb.rotation.z=THREE.MathUtils.degToRad(-52);thumb.position.set(.63,1.38,0);g.add(thumb);const springM=mat(0xaeb0b0,.7,.28);const pts:THREE.Vector3[]=[];for(let i=0;i<120;i++){const t=i/119*Math.PI*12;pts.push(new THREE.Vector3(Math.cos(t)*.46,-.1-i/119*2.25,Math.sin(t)*.46*.36));}const spring=new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(pts),180,.055,8,false),springM);spring.castShadow=true;g.add(spring);const base=box(1.82,.32,.92,mat(0xc3c4c4,.5,.45));base.position.y=-2.55;g.add(base);return g;}
function makeCandle(){const g=new THREE.Group();const body=cyl(.31,1.9,mat(WHITE,.05,.72));g.add(body);const wick=cyl(.028,.22,mat(0x3e3e3d,.05,.8),16);wick.position.y=1.04;g.add(wick);const flameMat=new THREE.MeshStandardMaterial({color:0xffc878,emissive:0xffa24f,emissiveIntensity:2.1,roughness:.25});const flame=new THREE.Mesh(new THREE.SphereGeometry(.18,24,18),flameMat);flame.scale.set(.72,1.5,.72);flame.position.y=1.35;flame.castShadow=false;g.add(flame);const light=new THREE.PointLight(0xffa95b,1.1,3.5,2);light.position.y=1.35;g.add(light);return g;}
function makeFlashlight(){const g=new THREE.Group();const body=cyl(.32,1.65,mat(0xaeb0b1,.55,.36));body.rotation.z=Math.PI/2;g.add(body);const head=cyl(.48,.5,mat(0x949697,.64,.29));head.rotation.z=Math.PI/2;head.position.x=.92;g.add(head);const lens=cyl(.36,.04,new THREE.MeshPhysicalMaterial({color:0xd9e0e2,roughness:.08,transmission:.35,transparent:true,opacity:.68}));lens.rotation.z=Math.PI/2;lens.position.x=1.19;g.add(lens);g.rotation.z=THREE.MathUtils.degToRad(32);return g;}
function makeMagnifier(){const g=new THREE.Group();const ring=new THREE.Mesh(new THREE.TorusGeometry(.78,.09,16,64),mat(0xaeb0b1,.58,.33));ring.castShadow=true;g.add(ring);const lens=new THREE.Mesh(new THREE.CircleGeometry(.69,64),new THREE.MeshPhysicalMaterial({color:0xdfe4e5,transparent:true,opacity:.18,transmission:.78,roughness:.05,metalness:0,side:THREE.DoubleSide}));g.add(lens);const handle=box(.22,1.55,.24,mat(0xa5a7a8,.55,.35));handle.position.set(.78,-1.14,0);handle.rotation.z=THREE.MathUtils.degToRad(-42);g.add(handle);return g;}
function makeButton(){const g=new THREE.Group();const base=cyl(.68,.24,mat(0xb6b7b7,.45,.44));base.rotation.x=Math.PI/2;g.add(base);const top=cyl(.37,.22,mat(RED,.18,.36));top.rotation.x=Math.PI/2;top.position.z=.18;g.add(top);return g;}
function makeBasket(){const g=new THREE.Group();const m=mat(0xaaaaaa,.45,.5);const bottom=box(1.3,.12,.55,m);bottom.position.y=-.74;g.add(bottom);for(const x of[-.62,.62]){const side=box(.1,1.55,.55,m);side.position.x=x;g.add(side);}for(let i=0;i<4;i++){const bar=box(.08,1.45,.58,m);bar.position.x=-.45+i*.3;g.add(bar);}return g;}
function addRope(scene:THREE.Scene,a:THREE.Vector3,b:THREE.Vector3,c?:THREE.Vector3){const pts=c?[a,c,b]:[a,b];const curve=new THREE.CatmullRomCurve3(pts);const mesh=new THREE.Mesh(new THREE.TubeGeometry(curve,48,.065,8,false),mat(ROPE,.02,.86));mesh.castShadow=true;scene.add(mesh);return mesh;}

function installDom(){document.body.innerHTML=`<main class="clean01-shell" id="clean01-shell"><section class="clean01-stage"><canvas id="clean01-canvas" aria-label="Игровое поле Level 01"></canvas></section><header class="clean01-top"><div class="clean01-top-left"><button class="clean01-icon" id="clean01-menu" aria-label="Меню">☰</button><span class="clean01-level">01</span></div><div class="clean01-top-right"><button class="clean01-play" id="clean01-play" aria-label="Запустить">▶</button></div></header><div class="clean01-hint">перетаскивай · вращай · соединяй</div><footer class="clean01-shelf"><div class="clean01-parts"><button class="clean01-part" data-part="ball"><span class="clean01-preview"><i class="clean01-ball"></i></span><span class="clean01-label">Шар</span></button><button class="clean01-part" data-part="ramp"><span class="clean01-preview"><i class="clean01-ramp"></i></span><span class="clean01-label">Рампа</span></button><button class="clean01-part" data-part="rope"><span class="clean01-preview"><i class="clean01-rope"></i></span><span class="clean01-label">Верёвка</span></button><button class="clean01-part" data-part="pulley"><span class="clean01-preview"><i class="clean01-pulley"></i></span><span class="clean01-label">Шкив</span></button><button class="clean01-part" data-part="fan"><span class="clean01-preview"><i class="clean01-fan"></i></span><span class="clean01-label">Вентилятор</span></button><button class="clean01-part" data-part="candle"><span class="clean01-preview"><i class="clean01-candle"></i></span><span class="clean01-label">Свеча</span></button><button class="clean01-part" data-part="flashlight"><span class="clean01-preview"><i class="clean01-flashlight"></i></span><span class="clean01-label">Фонарик</span></button><button class="clean01-part" data-part="magnifier"><span class="clean01-preview"><i class="clean01-magnifier"></i></span><span class="clean01-label">Лупа</span></button><button class="clean01-part" data-part="button"><span class="clean01-preview"><i class="clean01-button-preview"></i></span><span class="clean01-label">Кнопка</span></button><button class="clean01-part" data-part="basket"><span class="clean01-preview"><i class="clean01-basket"></i></span><span class="clean01-label">Цель</span></button></div></footer><div class="clean01-toast" id="clean01-toast"></div></main>`;}

export function installCleanMinimalLevel01():void{
 installDom();
 const shell=document.querySelector<HTMLElement>('#clean01-shell')!;
 const canvas=document.querySelector<HTMLCanvasElement>('#clean01-canvas')!;
 const play=document.querySelector<HTMLButtonElement>('#clean01-play')!;
 const menu=document.querySelector<HTMLButtonElement>('#clean01-menu')!;
 const toast=document.querySelector<HTMLElement>('#clean01-toast')!;
 const stage=document.querySelector<HTMLElement>('.clean01-stage')!;
 const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:'high-performance'});
 renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
 const scene=new THREE.Scene();scene.background=new THREE.Color(0xf2f2f0);
 const camera=new THREE.PerspectiveCamera(20,4/3,.1,100);camera.position.set(0,.45,42);camera.lookAt(0,0,0);
 const hemi=new THREE.HemisphereLight(0xffffff,0xdadad6,2.35);scene.add(hemi);const key=new THREE.DirectionalLight(0xfffdf8,3.8);key.position.set(-8,13,18);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-18;key.shadow.camera.right=18;key.shadow.camera.top=14;key.shadow.camera.bottom=-12;key.shadow.bias=-.00008;scene.add(key);const fill=new THREE.DirectionalLight(0xffffff,1.15);fill.position.set(10,5,12);scene.add(fill);
 const wall=new THREE.Mesh(new THREE.PlaneGeometry(40,28),new THREE.MeshStandardMaterial({color:0xf2f2f0,roughness:.92,metalness:0}));wall.position.z=-1.7;wall.receiveShadow=true;scene.add(wall);const floor=new THREE.Mesh(new THREE.PlaneGeometry(40,14),new THREE.MeshStandardMaterial({color:0xe8e8e6,roughness:.88,metalness:0}));floor.rotation.x=-Math.PI/2;floor.position.set(0,-6.25,1.6);floor.receiveShadow=true;scene.add(floor);
 const draggable:Draggable[]=[];const register=(root:THREE.Object3D,x:number,y:number,z=0)=>{root.position.set(x,y,z);scene.add(root);draggable.push({root,home:root.position.clone()});return root;};
 const pedestal=makePedestal();register(pedestal,-9.8,-.1,0);const ball=sphere(.56,mat(0xc8cacb,.82,.2));ball.position.set(-9.8,3.22,.1);scene.add(ball);draggable.push({root:ball,home:ball.position.clone()});
 const ramp=register(makeRamp(),-4.25,3.25,.08);const pulley=register(makePulley(),.55,5.15,.12);const weight=register(makeWeight(),.62,.65,.1);addRope(scene,new THREE.Vector3(.55,5.72,.12),new THREE.Vector3(.62,1.55,.1),new THREE.Vector3(.82,5.15,.12));
 const fan=register(makeFan(),8.6,1.2,.08);const glove=register(makeGlove(),-4.9,-3.25,.2);const candle=register(makeCandle(),-.55,-3.66,.24);const flashlight=register(makeFlashlight(),3.1,-3.85,.2);const magnifier=register(makeMagnifier(),6.0,-3.2,.2);const button=register(makeButton(),9.1,-4.8,.22);const basket=register(makeBasket(),11.25,-3.9,.1);
 const raycaster=new THREE.Raycaster();const pointer=new THREE.Vector2();const dragPlane=new THREE.Plane(new THREE.Vector3(0,0,1),0);const hit=new THREE.Vector3();let selected:THREE.Object3D|null=null;let dragOffset=new THREE.Vector3();let pointerId:number|null=null;let running=false;let t0=performance.now();
 const select=(obj:THREE.Object3D|null)=>{selected=obj;for(const d of draggable)d.root.traverse(o=>{if(o instanceof THREE.Mesh){const m=o.material as THREE.MeshStandardMaterial;m.emissive?.setHex(d.root===obj?0x111111:0x000000);}});};
 const norm=(e:PointerEvent)=>{const r=canvas.getBoundingClientRect();pointer.x=((e.clientX-r.left)/r.width)*2-1;pointer.y=-((e.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(pointer,camera);};
 canvas.addEventListener('pointerdown',e=>{norm(e);const meshes:THREE.Object3D[]=[];for(const d of draggable)d.root.traverse(o=>{if(o instanceof THREE.Mesh)meshes.push(o);});const intersections=raycaster.intersectObjects(meshes,false);if(!intersections.length){select(null);return;}let root=intersections[0].object;while(root.parent&&root.parent!==scene)root=root.parent;const match=draggable.find(d=>d.root===root);if(!match)return;select(match.root);pointerId=e.pointerId;canvas.setPointerCapture(e.pointerId);if(raycaster.ray.intersectPlane(dragPlane,hit))dragOffset.copy(match.root.position).sub(hit);});
 canvas.addEventListener('pointermove',e=>{if(pointerId!==e.pointerId||!selected||running)return;norm(e);if(raycaster.ray.intersectPlane(dragPlane,hit)){selected.position.x=THREE.MathUtils.clamp(hit.x+dragOffset.x,-12.4,12.4);selected.position.y=THREE.MathUtils.clamp(hit.y+dragOffset.y,-5.25,6.3);selected.position.z=.35;}});
 const release=(e:PointerEvent)=>{if(pointerId!==e.pointerId)return;pointerId=null;if(selected)selected.position.z=.1;};canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);
 canvas.addEventListener('wheel',e=>{if(!selected||running)return;e.preventDefault();selected.rotation.z+=Math.sign(e.deltaY)*THREE.MathUtils.degToRad(5);},{passive:false});
 let toastTimer=0;const notify=(msg:string)=>{toast.textContent=msg;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=window.setTimeout(()=>toast.classList.remove('show'),1800);};
 menu.addEventListener('click',()=>notify('Меню Level 01 будет подключено к карте этапов.'));
 play.addEventListener('click',()=>{running=!running;play.textContent=running?'■':'▶';play.classList.toggle('is-running',running);play.setAttribute('aria-label',running?'Остановить':'Запустить');if(!running){for(const d of draggable){d.root.position.copy(d.home);d.root.rotation.set(0,0,0);}ramp.rotation.z=0;flashlight.rotation.z=0;notify('Сцена возвращена в режим строительства.');}else{t0=performance.now();select(null);notify('Механизм запущен.');}});
 for(const b of document.querySelectorAll<HTMLButtonElement>('.clean01-part'))b.addEventListener('click',()=>{document.querySelectorAll('.clean01-part').forEach(x=>x.classList.remove('is-selected'));b.classList.add('is-selected');shell.classList.add('show-hint');window.setTimeout(()=>shell.classList.remove('show-hint'),1400);});
 const resize=()=>{const r=stage.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();};new ResizeObserver(resize).observe(stage);resize();
 const animate=(now:number)=>{const dt=Math.min((now-t0)/1000,20);if(running){const blades=fan.getObjectByName('fan-blades');if(blades)blades.rotation.z=-dt*4.2;weight.position.y=.65-Math.sin(dt*3.6)*.28*Math.exp(-dt*.15);glove.position.y=-3.25+Math.max(0,Math.sin(dt*4.4))*Math.exp(-dt*.24)*.35;}renderer.render(scene,camera);requestAnimationFrame(animate);};requestAnimationFrame(animate);
 window.dispatchEvent(new CustomEvent('clean01-ready'));
}
